version: "3"
services:
  Main:
    image: laijackai/php7.1-apache:latest
    networks:
      - backend
    volumes:
      - ./Main/:/var/www/
    ports: 
      - 80:80

  Account:
    image: laijackai/php7.1-apache:latest
    networks:
      - backend
    volumes:
      - ./Account/:/var/www/
    ports: 
      - 8081:80

  Product:
    image: laijackai/php7.1-apache:latest
    networks:
      - backend
    volumes:
      - ./Product/:/var/www/
    ports: 
      - 8082:80

  CartAndOrder:
    image: laijackai/php7.1-apache:latest
    networks:
      - backend
    volumes:
      - ./CartAndOrder/:/var/www/
    ports: 
      - 8083:80

  MySQL:
    image: mysql:5.7.21
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: microservice
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - backend
    ports: 
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
    environment:
      PMA_HOST: MySQL
      PMA_PORT: 3306
    ports:
      - '8084:80'

networks:
  backend:







    
